ALTER TABLE `vid_matchs` CHANGE `id` `id` INT(11) NOT NULL, CHANGE `team1_id` `team1_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `team2_id` `team2_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `data` `data` VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `video_src` `video_src` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `status_end` `status_end` VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'N';
ALTER TABLE `vid_actions` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, CHANGE `action_name` `action_name` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `action_type` `action_type` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `type` `type` TINYINT(1) NULL DEFAULT '0' COMMENT '\"1\"- goal keeper', CHANGE `time_before` `time_before` INT(5) NULL DEFAULT NULL, CHANGE `time_after` `time_after` INT(5) NULL DEFAULT NULL, CHANGE `event_type` `event_type` TINYINT(1) NULL DEFAULT '0' COMMENT '1-evnet 0-action', CHANGE `main_type` `main_type` TINYINT(1) NULL DEFAULT '0' COMMENT '1-show in main page', CHANGE `timer_role` `timer_role` VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'E', CHANGE `sorting` `sorting` INT(11) NULL DEFAULT NULL;
ALTER TABLE `vid_players` CHANGE `player_name` `player_name` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `player_number` `player_number` INT(3) NULL DEFAULT NULL;
ALTER TABLE `vid_match_players_number` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, CHANGE `match_id` `match_id` INT(11) NULL DEFAULT NULL, CHANGE `player_id` `player_id` VARCHAR(37) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE `number` `number` INT(3) NULL DEFAULT NULL;
ALTER TABLE `vid_player_positions` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, CHANGE `match_id` `match_id` INT(11) NULL DEFAULT NULL, CHANGE `player_id` `player_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `player_position` `player_position` INT(3) NULL DEFAULT NULL;
ALTER TABLE `vid_teams` CHANGE `team_name` `team_name` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `vid_events` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, CHANGE `match_id` `match_id` INT(11) NULL DEFAULT NULL, CHANGE `action_id` `action_id` INT(11) NULL DEFAULT NULL, CHANGE `player1_id` `player1_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `player2_id` `player2_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `time_game` `time_game` INT(5) NULL DEFAULT NULL, CHANGE `time_video` `time_video` INT(5) NULL DEFAULT NULL, CHANGE `success` `success` TINYINT(1) NULL DEFAULT NULL COMMENT '1-Yes 0-No', CHANGE `card_yellow` `card_yellow` TINYINT(1) NULL DEFAULT NULL, CHANGE `card_red` `card_red` TINYINT(1) NULL DEFAULT NULL, CHANGE `visible` `visible` TINYINT(1) NULL DEFAULT '1', CHANGE `full_geolocation` `full_geolocation` TINYINT(2) NULL DEFAULT NULL, CHANGE `half_geolocation` `half_geolocation` TINYINT(2) NULL DEFAULT NULL, CHANGE `half_time` `half_time` TINYINT(1) NULL DEFAULT NULL, CHANGE `favorite` `favorite` TINYINT(1) NULL DEFAULT NULL, CHANGE `sec_action_id` `sec_action_id` INT(11) NULL DEFAULT NULL, CHANGE `sec_player1_id` `sec_player1_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `sec_player2_id` `sec_player2_id` VARCHAR(37) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `sec_success` `sec_success` TINYINT(1) NULL DEFAULT NULL COMMENT '1-Yes 0-No', CHANGE `sec_full_geolocation` `sec_full_geolocation` TINYINT(2) NULL DEFAULT NULL, CHANGE `time_from` `time_from` INT(5) NULL DEFAULT NULL, CHANGE `time_to` `time_to` INT(5) NULL DEFAULT NULL, CHANGE `video_src` `video_src` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `status_video` `status_video` TINYINT(1) NULL DEFAULT NULL COMMENT '0-local,1-server';
------14-03-2016-----------
ALTER TABLE `vid_teams` CHANGE `team_name` `team_name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

